services:
  mysql-db:
    image: mysql:8.0

    ports:
      - "3306:3306"

    container_name: mysql_database

    environment:
      MYSQL_ROOT_PASSWORD: api123
      MYSQL_DATABASE: wallet_homolog
      MYSQL_USER: wallet_api_homolog
      MYSQL_PASSWORD: api123

    volumes:
      - mysql-data:/var/lib/mysql

    restart: always

volumes:
  mysql-data: